services:
  - type: web
    name: pocasie-ecmwf
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
